// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrvkgerfvxijlvxzstnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydmtnZXJmdnhpamx2eHpzdG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjU5MTEsImV4cCI6MjA2MDc0MTkxMX0.sBmX1_cR5a2GHkogUOBx_RQj3i_PbD8jLiOYk3NrTnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);